name: Deploy Frontend to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ ! -d "/home/EmployeeAI_FE" ]; then
              mkdir -p /home/EmployeeAI_FE
              cd /home/EmployeeAI_FE
              git clone https://${{ secrets.PAT_TOKEN }}@github.com/CN-LEON-DX/EmployeeAI_FE.git .
            else
              cd /home/EmployeeAI_FE
              if [ -d ".git" ]; then
                git pull
              else
                cd ..
                rm -rf EmployeeAI_FE
                mkdir -p EmployeeAI_FE
                cd EmployeeAI_FE
                git clone https://${{ secrets.PAT_TOKEN }}@github.com/CN-LEON-DX/EmployeeAI_FE.git .
              fi
            fi
            
            cd /home/EmployeeAI_FE
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
            docker system prune -f
