name: Deploy Frontend to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/EmployeeAI_FE
            git pull https://${{ secrets.PAT_TOKEN }}@github.com/OWNER/EmployeeAI_FE.git main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker system prune -f
